name: Docker Build Image
description: "Action to Build the Project Docker Image"

inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
    default: 'Dockerfile'
  image_name:
    description: "Image name"
    required: true
  tag_name:
    description: "Docker Image Tag name"
    default: ''

runs:
  using: composite
  steps:
    - name: Set TAG variable
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          TAG=$(date +%s)
        else
          TAG="${{ inputs.tag_name }}"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Define Docker Image name
      run: echo "DOCKER_IMAGE_NAME=mariacosta870/${{ inputs.image_name }}:$TAG" >> $GITHUB_ENV
      shell: bash

    - name: Docker Build
      run: docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash

    - name: Verify Docker Images
      run: docker images
      shell: bash
