name: Docker Build Image
description: "Action to Build the Project Docker Image"

inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
    default: 'Dockerfile'
  image_name:
    description: "Image name"
  tag_name:
    description: "Docker Image Tag name"

runs:
  using: composite
  steps:
    - name: Define Tag name
      run: |
       if [ -z "${{ inputs.tag_name }}" ]; 
          then export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi 
        docker build . --file ${{ inputs.path_dockerfile }} --tag 'mariacosta870/mod_cicd${{ inputs.image_name }}':$TAG
      shell: bash

    - name: Define Image name
      run: echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:${{ env.TAG }}" >> $GITHUB_ENV
      shell: bash

    - name: Docker Build
      run: docker build .  --file ${{ inputs.path_dockerfile }} --tag ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash

    - name: Verify Docker Images
      run: docker images
      shell: bash
